### ISSUE TITLE
NVE to NVT configuration file

### ISSUE THREAD

**Issue by tmtobias** [tmtobias/ferrofluid#12]
Please, provide configuration file with "NVT" ensemble.

**Comment by tmtobias** [comment]
done!

**Comment by mvala** [comment]
Does it work?

**Comment by mvala** [comment]
What is filename?

**Comment by mvala** [comment]
What branch? I would like to test it and then we close it

**Comment by tmtobias** [comment]
It is on branch issue_9, filename "my.omd". Now, I think it is not good, after parameters have changed an error with tauBarostat occured

**Comment by mvala** [comment]
Ok i will have look

**Comment by tmtobias** [comment]
can't download file SimA0_3.omd, command "git checkout issue_9 SimA0_3.omd" doesn't work. Do you know where is the problem?

**Comment by mvala** [comment]
if you are in branch issue_9. then you do
```
git pull
```

**Comment by tmtobias** [comment]
Ok, thank you

**Comment by tmtobias** [comment]
after "omd-run" FATAL ERROR:
	StatWriter detected a numerical error writing: Total Energy

**Comment by mvala** [comment]
Did you repeat these 2 commands?

**Comment by tmtobias** [comment]
yes, still fatal error

**Comment by mvala** [comment]
Fixed. Force was set too high in your laptop
