### ISSUE TITLE
Install OpenMD

### ISSUE THREAD

**Issue by mvala** [tmtobias/ferrofluid#5]
I will prepare rpm and i will give you instruction when ready

**Comment by mvala** [comment]
Openmd needs qhull and it is building now at https://copr.fedorainfracloud.org/coprs/mvala/saske/build/462245/

**Comment by mvala** [comment]
Openmd is building now at https://copr.fedorainfracloud.org/coprs/mvala/saske/build/462255/

**Comment by mvala** [comment]
Ok. On fc24 it is build ok. So you will install it with following commands.

As root you do

Add saske repository (only one time) . Please answer "y"
```
dnf copr enable mvala/saske
```

Install openmd
```
dnf install openmd
```
And it should be it. Please close issue when ok. If not write error

**Comment by tmtobias** [comment]
error: nothing provides limpbi.so.12( )( 64 bit ) needed by openmd-2.4.1-0.fc24.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)

**Comment by tmtobias** [comment]
Doesn't work with command '--allowerasing'.

**Comment by mvala** [comment]
i see, i have the same problem. Looking to it now

**Comment by mvala** [comment]
I should be fixed now. It is building at https://copr.fedorainfracloud.org/coprs/mvala/saske/build/463543/
WHen success you can install it via
```
dnf clean all
dnf install openmd
```
